const Map<String, List<String>> kExerciseAliases = {
  'Alternate Lateral Pulldown': ['Lat Pulldown Single Arm (Cable)'],
  'Assisted Chest Dip (Kneeling)': ['Chest Dip (Assisted)'],
  'Assisted Pull-up': ['Pull Up (Assisted)', 'Assisted Pull Up (Machine)'],
  'Band Pull-Apart': ['Band Pullaparts'],
  'Barbell Bench Press': ['Bench Press (Barbell)', 'Flat Bench Press'],
  'Barbell Bent Over Row': ['Bent Over Row (Barbell)', 'Barbell Row'],
  'Barbell Clean and Press': ['Clean and Press (Barbell)'],
  'Barbell Close-grip Bench Press': ['Close Grip Bench Press (Barbell)'],
  'Barbell Curl': ['Bicep Curl (Barbell)', 'Barbell Bicep Curl'],
  'Barbell Deadlift': ['Deadlift (Barbell)', 'Conventional Deadlift'],
  'Barbell Decline Bench Press': ['Decline Bench Press (Barbell)'],
  'Barbell Front Squat': ['Front Squat (Barbell)'],
  'Barbell Full Squat': [
    'Squat (Barbell)',
    'Back Squat',
    'Back Squat (Barbell)',
    'Barbell Squat',
    'High Bar Squat',
  ],
  'Barbell Glute Bridge': ['Glute Bridge (Barbell)'],
  'Barbell Good Morning': ['Good Morning (Barbell)'],
  'Barbell Hack Squat': ['Hack Squat (Barbell)'],
  'Barbell Incline Bench Press': ['Incline Bench Press (Barbell)'],
  'Barbell Lying Triceps Extension': ['Skullcrusher (Barbell)', 'Lying Triceps Extension (Barbell)'],
  'Barbell Overhead Squat': ['Overhead Squat (Barbell)'],
  'Barbell Pendlay Row': ['Pendlay Row (Barbell)'],
  'Barbell Preacher Curl': ['Preacher Curl (Barbell)'],
  'Barbell Reverse Curl': ['Reverse Curl (Barbell)'],
  'Barbell Reverse Wrist Curl': ['Reverse Wrist Curl (Barbell)'],
  'Barbell Rollerout': ['Ab Wheel', 'Ab Wheel Rollout'],
  'Barbell Romanian Deadlift': ['Romanian Deadlift (Barbell)'],
  'Barbell Seated Calf Raise': ['Seated Calf Raise (Barbell)'],
  'Barbell Shrug': ['Shrug (Barbell)'],
  'Barbell Single Leg Split Squat': ['Bulgarian Split Squat (Barbell)'],
  'Barbell Standing Calf Raise': ['Standing Calf Raise (Barbell)'],
  'Barbell Standing Wide Military Press': [
    'Overhead Press (Barbell)',
    'Shoulder Press (Barbell)',
    'Military Press (Barbell)',
    'Standing Military Press',
  ],
  'Barbell Straight Leg Deadlift': ['Stiff Leg Deadlift (Barbell)'],
  'Barbell Sumo Deadlift': ['Sumo Deadlift (Barbell)'],
  'Barbell Wrist Curl': ['Wrist Curl (Barbell)'],
  'Belt Squat': ['Belt Squat (Machine)'],
  'Bench Dip (Knees Bent)': ['Bench Dip'],
  'Bicycle Crunch': ['Bicycle Crunch (Bodyweight)'],
  'Bodyweight Squat': ['Squat', 'Squat (Bodyweight)', 'Air Squat'],
  'Cable Cross-over Variation': ['Cable Fly Crossovers', 'Chest Fly (Cable)'],
  'Cable Curl': ['Bicep Curl (Cable)'],
  'Cable Front Raise': ['Front Raise (Cable)'],
  'Cable Hammer Curl (With Rope)': ['Hammer Curl (Cable)'],
  'Cable Kickback': ['Triceps Kickback (Cable)'],
  'Cable Kneeling Crunch': ['Cable Crunch', 'Kneeling Crunch (Cable)'],
  'Cable Lateral Raise': ['Lateral Raise (Cable)'],
  'Cable Overhead Triceps Extension (Rope Attachment)': [
    'Triceps Extension (Cable)',
    'Overhead Tricep Extension (Cable)',
  ],
  'Cable Pulldown': ['Lat Pulldown (Cable)', 'Lat Pulldown (Machine)', 'Lat Pulldown'],
  'Cable Pushdown': ['Triceps Pushdown (Cable)', 'Tricep Pushdown'],
  'Cable Seated Row': ['Seated Cable Row', 'Seated Row (Cable)', 'Seated Cable Row - Bar Grip'],
  'Cable Shrug': ['Shrug (Cable)'],
  'Chin-up': ['Chin Up'],
  'Close-Grip Lat Pulldown': ['Lat Pulldown - Close Grip (Cable)'],
  'Crunch Floor': ['Crunch', 'Crunch (Bodyweight)'],
  'Dead Hang': ['Bar Hang', 'Hang'],
  'Dumbbell Alternate Preacher Curl': ['Preacher Curl (Dumbbell)'],
  'Dumbbell Arnold Press': ['Arnold Press (Dumbbell)'],
  'Dumbbell Bench Press': ['Bench Press (Dumbbell)'],
  'Dumbbell Bent Over Row': ['Bent Over Row (Dumbbell)'],
  'Dumbbell Biceps Curl': ['Bicep Curl (Dumbbell)', 'Dumbbell Bicep Curl'],
  'Dumbbell Concentration Curl': ['Concentration Curl (Dumbbell)'],
  'Dumbbell Deadlift': ['Deadlift (Dumbbell)'],
  'Dumbbell Decline Bench Press': ['Decline Bench Press (Dumbbell)'],
  'Dumbbell Fly': ['Chest Fly (Dumbbell)', 'Dumbbell Flyes'],
  'Dumbbell Front Raise': ['Front Raise (Dumbbell)'],
  'Dumbbell Goblet Squat': ['Goblet Squat (Dumbbell)'],
  'Dumbbell Hammer Curl': ['Hammer Curl (Dumbbell)'],
  'Dumbbell Hip Thrust': ['Hip Thrust (Dumbbell)'],
  'Dumbbell Incline Bench Press': ['Incline Bench Press (Dumbbell)'],
  'Dumbbell Lateral Raise': ['Lateral Raise (Dumbbell)', 'Side Lateral Raise'],
  'Dumbbell Lunge': ['Lunge (Dumbbell)', 'Walking Lunge (Dumbbell)'],
  'Dumbbell Pullover': ['Pullover (Dumbbell)'],
  'Dumbbell Reverse Fly': ['Reverse Fly (Dumbbell)', 'Rear Delt Fly (Dumbbell)'],
  'Dumbbell Seated Calf Raise': ['Seated Calf Raise (Dumbbell)'],
  'Dumbbell Shrug': ['Shrug (Dumbbell)'],
  'Dumbbell Single Leg Split Squat': ['Bulgarian Split Squat (Dumbbell)'],
  'Dumbbell Standing Calf Raise': ['Standing Calf Raise (Dumbbell)'],
  'Dumbbell Standing Overhead Press': ['Shoulder Press (Dumbbell)', 'Overhead Press (Dumbbell)'],
  'Dumbbell Standing Triceps Extension': [
    'Triceps Extension (Dumbbell)',
    'Overhead Tricep Extension (Dumbbell)',
  ],
  'Elliptical Trainer': ['Elliptical Machine', 'Elliptical'],
  'Face Pull': ['Face Pull (Cable)'],
  'Hiking': ['Hike'],
  'Hip Abduction Machine': ['Hip Abduction (Machine)'],
  'Hip Adduction Machine': ['Hip Adduction (Machine)'],
  'Hip Thrust': ['Hip Thrust (Bodyweight)'],
  'Incline Dumbbell Curl': ['Incline Curl (Dumbbell)'],
  'Jump Rope': ['Skipping Rope'],
  'Kettlebell Farmer Carry': ['Farmers Walk', 'Farmers Carry'],
  'Kettlebell Goblet Squat': ['Goblet Squat (Kettlebell)'],
  'Kettlebell Overhead Press': ['Overhead Press (Kettlebell)'],
  'Kettlebell Romanian Deadlift': ['Romanian Deadlift (Kettlebell)'],
  'Knee Push-up': ['Knee Push Up (Bodyweight)'],
  'Landmine Press': ['Landmine Press (Barbell)'],
  'Leg Extension': ['Knee Extension'],
  'Lever Seated Reverse Fly': ['Rear Delt Reverse Fly (Machine)', 'Reverse Fly (Machine)'],
  'Lever Seated Row': ['Seated Row (Machine)', 'Iso-Lateral Row (Machine)'],
  'Lever Shoulder Press': ['Shoulder Press (Machine)', 'Seated Shoulder Press (Machine)'],
  'Lever Shrug': ['Shrug (Machine)'],
  'Lever Standing Calf Raise': ['Standing Calf Raise (Machine)', 'Calf Raise (Machine)'],
  'Lever Standing Chest Press': ['Chest Press (Machine)', 'Seated Chest Press (Machine)'],
  'Lever T Bar Row': ['T Bar Row', 'T Bar Row (Machine)'],
  'Lever Triceps Extension': ['Triceps Extension (Machine)'],
  'Lying Leg Raise': ['Leg Raise (Bodyweight)'],
  'Machine Glute Kickback': ['Glute Kickback (Machine)'],
  'Machine Lateral Raise': ['Lateral Raise (Machine)'],
  'Meadows Row': ['Meadows Row (Barbell)'],
  'One-Arm Dumbbell Row': ['Single Arm Dumbbell Row', 'Dumbbell Row'],
  'Outdoor Cycling': ['Cycling', 'Biking', 'Bike Ride', 'Road Cycling'],
  'Outdoor Run': ['Running', 'Run', 'Jogging', 'Jog'],
  'Pec Deck': ['Chest Fly (Machine)', 'Pec Deck (Machine)', 'Butterfly (Machine)'],
  'Plank': ['Front Plank', 'Forearm Plank'],
  'Power Clean': ['Power Clean (Barbell)'],
  'Pull-up': ['Pull Up'],
  'Push-up': ['Push Up (Bodyweight)', 'Press Up'],
  'Mountain Climber': ['Mountain Climbers'],
  'Reverse Lunge': ['Reverse Lunge (Bodyweight)'],
  'Rope Tricep Pushdown': ['Triceps Rope Pushdown (Cable)'],
  'Rowing Machine': ['Rowing (Machine)', 'Rowing'],
  'Russian Twist': ['Russian Twist (Bodyweight)'],
  'Seated Leg Curl': ['Leg Curl (Machine)', 'Seated Leg Curl (Machine)'],
  'Side Plank': ['Side Bridge'],
  'Single Dumbbell Skullcrusher': ['Skullcrusher (Dumbbell)', 'Skull Crusher'],
  'Single-Arm Cable Row': ['Seated Row Single Arm (Cable)'],
  'Ski Erg': ['Ski Machine'],
  'Smith Bench Press': ['Bench Press (Smith Machine)'],
  'Smith Hack Squat': ['Hack Squat (Machine)'],
  'Smith Machine Bicep Curl': ['Bicep Curl (Smith Machine)'],
  'Smith Machine Bulgarian Split Squat': ['Bulgarian Split Squat (Smith Machine)'],
  'Smith Seated Shoulder Press': ['Shoulder Press (Smith Machine)'],
  'Stair Climber': ['Stair Machine', 'Stairmaster'],
  'Stationary Bike': ['Cycling (Indoor)', 'Indoor Cycling'],
  'Swimming': ['Swim', 'Pool Swim'],
  'Trap Bar Deadlift': ['Deadlift (Trap Bar)', 'Hex Bar Deadlift'],
  'Treadmill Run': ['Running (Treadmill)', 'Treadmill'],
  'Treadmill Walk': ['Walking (Treadmill)'],
  'Triceps Dip': ['Triceps Dip (Bodyweight)', 'Tricep Dip'],
  'Upright Row': ['Upright Row (Barbell)', 'Upright Row (Cable)'],
  'Walk': ['Walking', 'Outdoor Walk'],
  'Weighted Front Plank': ['Weighted Plank', 'Plank (Weighted)'],
  'Weighted Hanging Leg-hip Raise': ['Hanging Leg Raise'],
  'Weighted Pull-up': ['Pull Up (Weighted)'],
  'Weighted Russian Twist': ['Russian Twist (Weighted)'],
  'Wide-Grip Lat Pulldown': ['Lat Pulldown - Wide Grip (Cable)'],
};
